### ISSUE TITLE
Update bundle libs

### ISSUE THREAD

**Issue by milustreamer** [pwiecz/go-fltk#25]
Hello, is there a possibility that the bundle libs for gofltk will be updated and also added for apple m1?
I did this in the private workspace for apple m1, but the function signatures in the fltk 1.4 master have now been changed.
----------------
Example image.cxx :
int go_fltk_image_fail(Fl_Image *i) {
     return i->fail();
}
to
int go_fltk_image_fail(const Fl_Image *i) {
     return i->fail();
}
---------------
best regards

**Comment by pwiecz** [comment]
Hi,
I've updated bundled include files and libs to commit https://github.com/fltk/fltk/commit/237c0c1393dd9fe6f6c9ec8fb943141751c162bd . 
Hi @MoAlyousef , could you update the MacOS/x64 libs?
Probably we should split the header files for different architectures as well, so that they can be updated independently...

**Comment by MoAlyousef** [comment]
Hi
I've built newer macos libs (also against https://github.com/fltk/fltk/commit/237c0c1393dd9fe6f6c9ec8fb943141751c162bd) in my fork. I've also added arm64 libs, however I can't test that they work since I don't have an arm64 mac.
Also I'm unsure of the cgo directive for linking them, currently I've added:
```
#cgo arm64,darwin
```

**Comment by pwiecz** [comment]
Thanks!, I think that directive is the correct one.

**Comment by milustreamer** [comment]
Hi ,
I have test my program and the programs in the example directory ( also in opengl ).
they works for me.
thanks
