### ISSUE TITLE
TextEditor undo crashes

### ISSUE THREAD

**Issue by mark-summerfield** [pwiecz/go-fltk#92]
If I run https://github.com/mark-summerfield/gviz and immediatetly do Ctrl+Z or Edit->Undo (i.e., when there is nothing to be undone) the app crashes. The same thing happens if I do Ctrl+Shift+Z or Edit->Redo when there's nothing to be redone.

```
Unrecoverable error: runtime error: invalid memory address or nil pointer dereference
```
When I wrapped Fl_Text_Editor::undo() I used the same code pattern as was already in place for cut/copy/paste. But should I now add a check, e.g., changing,

```go
func (t *TextEditor) Undo() {
	C.go_fltk_TextEditor_undo((*C.Fl_Text_Editor)(t.ptr()))
}
```
to, say,
```go
func (t *TextEditor) Undo() {
        if p := t.ptr(); p != nil {
        	C.go_fltk_TextEditor_undo((*C.Fl_Text_Editor)(p))
        }
}
```
However, I suspect that the problem is elsewhere since none of the cut/copy/paste methods check the pointer deref. In which case, could it be a problem in FLTK itself?

**Comment by mark-summerfield** [comment]
The workaround I'm using in my own code is this:
```go
	if me.editor.Changed() != 0 {
		me.editor.Undo()
	}
```
and the equivalent for redo.

I could of course put this in the go-fltk source, e.g.,  something like:
```go
func (t *TextEditor) Undo() {
	if p := t.ptr(); p != nil && (*C.Fl_Widget)(p)->Changed() != 0 {
		C.go_fltk_TextEditor_undo((*C.Fl_Text_Editor)(p))
	}
}
```
What d'you think?

**Comment by MoAlyousef** [comment]
fltk-rs checks for a valid buffer prior to calling undo (it does so for many other TextEditor methods). So this could also be employed in Go. 
I can't really test though since I can't reproduce the crash on my system!

**Comment by pwiecz** [comment]
@mark-summerfield  This issue seems to be a bug in `gviz` not related to `go-fltk`.
When I run `gviz@v0.4.2` , I can trigger crash not only by pressing Ctrl-Z, but also e.g. pressing the "Scissors" button from the toolbar.
It's cause by lines such as: 
`menuBar.AddEx("Edit/&Undo", fltk.CTRL+'z', me.editor.Undo, fltk.MENU_VALUE)` in  https://github.com/mark-summerfield/gviz/blob/d3d53c3efca8929a2176bb734b47868cdad7e634/app.go#L95 when the `me.editor` is still nil.
It will make CTRL+z to trigger call to function on a `nil` object. After any edit the focus is on the text editor itself so Ctrl+Z is handled by the TextEditor's own keyboard handling and the callback is not being called.

**Comment by mark-summerfield** [comment]
I'm sorry, this was my mistake. I now no longer call the TextEditor methods directly, but always with a guard, e.g.,
```go
func (me *App) onEditCut() {
	if me.editor != nil {
		me.editor.Cut()
	}
}
```
etc.

Thanks!
